[Rainmeter]
AccurateText=1
DynamicWindowSize=1
Update=1000
MiddleMouseDownAction=!Refresh #CURRENTCONFIG#
MouseOverAction=[!ShowMeterGroup Hover][!ShowMeterGroup #stowAwayName#][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!HideMeterGroup Hover][!HideMeterGroup #stowAwayName#][!UpdateMeter *][!Redraw]

RightMouseDownAction=[!SkinCustomMenu]

ContextTitle=Edit Music Variables
ContextAction=["#@#\variables.inc"]

ContextTitle2=Smaller Size (0.8)
ContextAction2=[!WriteKeyValue Variables SCALE "(#SCREENAREAWIDTH#*0.000520833333325754-0.2)"][!Refresh]

ContextTitle3=Normal Size (1.0)
ContextAction3=[!WriteKeyValue Variables SCALE "(#SCREENAREAWIDTH#*0.000520833333325754)"][!Refresh]

ContextTitle4=Bigger Size (1.2)
ContextAction4=[!WriteKeyValue Variables SCALE "(#SCREENAREAWIDTH#*0.000520833333325754+0.2)"][!Refresh]

ContextTitle5=----
ContextAction5=[]

ContextTitle6=Standard Context Menu
ContextAction6=[!SkinMenu]

[Metadata]
Name=Music
Author=Thanh Tung
Information=Music Player
Version=1.0
License=CC BY-NC-SA 4.0

[Variables]
@include=#@#variables.inc
@include2=#@#color.inc
SCALE=1

[Shadow]
Meter=Image
SolidColor=77,73,62,200
X=5
Y=5
W=(#SCALE#*300)
H=(#SCALE#*350)
DynamicVariables=1

[Background]
Meter=Image
ImageName=#@#Underlay\Music.png
W=(#SCALE#*300)
H=(#SCALE#*350)

[mVolume]
Measure=Plugin
Plugin=Win7AudioPlugin

[mVolume2]
Measure=Calc
Formula=mVolume
IfCondition=(mVolume2 = -1)
IfTrueAction=[!SetOption "Text2.Volume" "Text" "Muted"][!Update]
IfFalseAction=[!SetOption "Text2.Volume" "Text" "%1%"][!Update]
 
[Text.Volume]
Meter=String
MeasureName=mVolume
X=(#SCALE#*12)
Y=(#SCALE#*230)
Text=VOLUME
FontFace=#thickFont#
FontColor=#opaque#
FontSize=(#SCALE#*12)
StringAlign=Left
AntiAlias=1

[Bar.Volume]
Meter=Bar
MeasureName=mVolume
X=(#SCALE#*13)
Y=(#SCALE#*250)
W=(#SCALE#*275)
H=(#SCALE#*5)
BarColor=#opaque#
SolidColor=#translucent#
BarOrientation=Horizontal
LeftMouseDownAction=[!CommandMeasure "mVolume" "SetVolume $MouseX:%$"][!Update]
MouseScrollDownAction=[!CommandMeasure "mVolume" "ChangeVolume -5"][!Update]
MouseScrollUpAction=[!CommandMeasure "mVolume" "ChangeVolume +5"][!Update]
 
[Text.Title]
Meter=String
X=(#SCALE#*12)
Y=(#SCALE#*6)
Text=Sound
FontFace=#thickFont#
FontSize=(#SCALE#*14)
FontColor=240,237,227,255
StringAlign=Left
AntiAlias=1

[mTitle]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=TITLE

[mArtist]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=ARTIST

[mAlbum]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=ALBUM

[mPosition]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=POSITION

; mPosition2 will not show progress, but instead the time the track was started
[mPosition2]
Measure=Plugin
Plugin=Plugins\QuotePlugin.dll
PathName=#unpDirectory#unp_time_started.txt
Subfolders=0
UpdateDivider=10

[mLength]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=DURATION

[mProgress]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=PROGRESS

[mStateButton]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=STATE
Substitute="0":"play","1":"pause","2":"play"

[mStatus]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=STATE

[mVersionEvaluator]
Measure=Calc
Formula=[mVersion]
DynamicVariables=1
 
;;==========================================
;   Styles
;;==========================================

[styleTextControls]
FontFace=#thickFont#
FontSize=(#SCALE#*10)
AntiAlias=1
FontColor=#translucent#
StringAlign=#interfaceTextAlignment#
DynamicVariables=1
Group=Hover
MouseActionCursor=1

[styleTextMini]
FontFace=#thickFont#
FontSize=(#SCALE#*5)
AntiAlias=1
FontColor=#opaque#
StringAlign=#interfaceTextAlignment#
DynamicVariables=1
Group=Hover

[styleTextMajor]
H=(#SCALE#*15)
FontSize=(#SCALE#*10)
FontColor=#opaque#
AntiAlias=1

[Now]
Meter=String
Text=Now
StringCase=Upper
StringAlign=#interfaceTextAlignment#
FontSize=(#SCALE#*12)
FontColor=#opaque#
X=(#SCALE#*80)
Y=(#SCALE#*287)
AntiAlias=1
FontFace=#thickFont#
UpdateDivider=-1
Hidden=#stowAway#
Group=Stow

[Playing]
Meter=String
Text=Playing
StringCase=Upper
StringAlign=#interfaceTextAlignment#
FontSize=(#SCALE#*12)
FontColor=#opaque#
X=(#SCALE#*80)
Y=(#SCALE#*307)
AntiAlias=1
FontFace=#thickFont#
UpdateDivider=-1
Hidden=#stowAway#
Group=Stow

[Hairline]
Meter=Bar
MeasureName=mProgress
X=(#SCALE#*90)
Y=(#SCALE#*270)
W=(#SCALE#*2)
H=(#SCALE#*70)
BarColor=#opaque#
SolidColor=#translucent#
BarOrientation=Vertical
ToolTipText="Progress Bar"
UpdateDivider=4
Hidden=#stowAway#
Group=Stow

[TopText]
Meter=String
MeterStyle=styleTextMajor
MeasureName=mArtist
X=(#SCALE#*100)
Y=(#SCALE#*280)
FontSize=(#SCALE#*17)
FontFace=#thinFont#
Text="%1"
ClipString=2
DynamicVariables=1
W=(#SCALE#*200)
H=(#SCALE#*22)
ToolTipText="%1"

[BottomText]
Meter=String 
MeterStyle=styleTextMajor
MeasureName=mTitle
X=(#SCALE#*100)
Y=(#SCALE#*305)
FontSize=(#SCALE#*18)
FontFace=#thickFont#
Text="%1" 
ClipString=2
DynamicVariables=1
W=(#SCALE#*200)
H=(#SCALE#*26)
ToolTipText="%1"

[Play]
MeterStyle=styleTextControls
Meter=String
MeasureName=mStateButton
X=(#SCALE#*85)
Y=(#SCALE#*270)
Text="%1"
LeftMouseDownAction=!CommandMeasure "mTitle" "PlayPause"
UpdateDivider=4
SolidColor=0,0,0,1

[Previous]
MeterStyle=styleTextControls
Meter=String
X=(#SCALE#*55)
Y=(#SCALE#*325)
Text="previous"
LeftMouseDownAction=!CommandMeasure "mTitle" "Previous"
UpdateDivider=-1

[Next]
MeterStyle=styleTextControls
Meter=String
X=(#SCALE#*85)
Y=(#SCALE#*325)
Text="next"
LeftMouseDownAction=!CommandMeasure "mTitle" "Next"
UpdateDivider=-1
SolidColor=0,0,0,1
