[Rainmeter]
Update=25
DynamicWindowSize=1
AccurateText=1

[Metadata]
Name=Nier Automata Alternative Visualizer
Author=Amtia
Version=1.0
License=CC BY-NC-SA 4.0

[MeterImage]
Meter=Image
ImageName=#@#Underlay\Visualizer.png
Y=(#SCALE#*31)
W=(#SCALE#*156)
H=(#SCALE#*25)
AntiAlias=1


[Variables]
SCALE=1.25

;;========================================
;  Measure
;;========================================

[MeasureAudio]
Measure=Plugin
Plugin=AudioLevel
Port=Output
FFTSize=2048
FFTOverlap=2048
FFTAttack=150
FFTDecay=300
Bands=21
FreqMin=20
FreqMax=20000
Sensitivity=25

[MeasureBand0]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=0

[MeasureBand1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1

[MeasureBand2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2

[MeasureBand3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3

[MeasureBand4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4

[MeasureBand5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5

[MeasureBand6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6

[MeasureBand7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7

[MeasureBand8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8

[MeasureBand9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9

[MeasureBand10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10

[MeasureBand11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11

[MeasureBand12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12

[MeasureBand13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13

[MeasureBand14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14

[MeasureBand15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15

[MeasureBand16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16

[MeasureBand17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17

[MeasureBand18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18

[MeasureBand19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19

[MeasureBand20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20

;;========================================
;  Styles
;;========================================

[MeterBand0]
Meter=Bar
MeasureName=MeasureBand0
X=0
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand1]
Meter=Bar
MeasureName=MeasureBand1
X=0
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand2]
Meter=Bar
MeasureName=MeasureBand2
X=(#SCALE#*8)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand3]
Meter=Bar
MeasureName=MeasureBand3
X=(#SCALE#*16)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand4]
Meter=Bar
MeasureName=MeasureBand4
X=(#SCALE#*24)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand5]
Meter=Bar
MeasureName=MeasureBand5
X=(#SCALE#*32)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand6]
Meter=Bar
MeasureName=MeasureBand6
X=(#SCALE#*40)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand7]
Meter=Bar
MeasureName=MeasureBand7
X=(#SCALE#*48)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand8]
Meter=Bar
MeasureName=MeasureBand8
X=(#SCALE#*56)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand9]
Meter=Bar
MeasureName=MeasureBand9
X=(#SCALE#*64)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand10]
Meter=Bar
MeasureName=MeasureBand10
X=(#SCALE#*72)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand11]
Meter=Bar
MeasureName=MeasureBand11
X=(#SCALE#*80)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand12]
Meter=Bar
MeasureName=MeasureBand12
X=(#SCALE#*88)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand13]
Meter=Bar
MeasureName=MeasureBand13
X=(#SCALE#*96)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand14]
Meter=Bar
MeasureName=MeasureBand14
X=(#SCALE#*104)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand15]
Meter=Bar
MeasureName=MeasureBand15
X=(#SCALE#*112)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand16]
Meter=Bar
MeasureName=MeasureBand16
X=(#SCALE#*120)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand17]
Meter=Bar
MeasureName=MeasureBand17
X=(#SCALE#*128)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand18]
Meter=Bar
MeasureName=MeasureBand18
X=(#SCALE#*136)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand19]
Meter=Bar
MeasureName=MeasureBand19
X=(#SCALE#*144)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical

[MeterBand20]
Meter=Bar
MeasureName=MeasureBand20
X=(#SCALE#*152)
Y=0 
BarImage=#@#Underlay\bar.png
BarOrientation=Vertical
