[Variables]
;Make changes as instructed below:
;YourUserName needs to be the user you are currently on. You can see it top right in the start menu.
YourUserName=Cold Damage

;Change YourGameFolder to the folder where you keep your games. 
;I reccommend making a folder and putting shortcuts to all your games there.
;But this is just my way of doing things so if you think you're so much better than me go ahead and delete the Games shortcuts
;I don't need your approval I'm popular with the ladies haha I swear hahaha please tell me I did a good job my life is a spiraling abyss
YourGameFolder=C:\Users\Cold damage\Documents\GAMES FOLDER

;Don't edit beyond here unless you know what you're doing or you want to fuck everything up, you ass
Font=Corbel
Size=15
Grey=160,160,160,220
Grey2=100,100,100,220
