[Metadata]
 Name=Status
 Author=Amtia
 Information=Status
 Version=1.0
 License=CC BY-NC-SA 4.0

[Variables]
@include=#@#Styles.inc
@include2=#@#disk.inc
Disk1=C:
Disk2=D:
SCALE=1
 
; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

[Shadow]
Meter=Image
SolidColor=77,73,62,200
X=5
Y=5
W=(#SCALE#*300)
H=(#SCALE#*350)
DynamicVariables=1

[Background]
Meter=Image
ImageName=#@#Underlay\Status.png
W=(#SCALE#*300)
H=(#SCALE#*350)

[Text.Title]
Meter=String
X=(#SCALE#*12)
Y=(#SCALE#*7)
Text=Status
FontFace=#thickFont#
FontSize=(#SCALE#*15)
FontColor=240,237,227,255
StringAlign=Left
AntiAlias=1
 
[Text.Title1]
Meter=String
X=(#SCALE#*12)
Y=(#SCALE#*43)
Text=2B
FontFace=#thickFont#
FontSize=(#SCALE#*15)
FontColor=64,61,52,255
StringAlign=Left
AntiAlias=1
 
[Text.Title2]
Meter=String
X=(#SCALE#*235)
Y=(#SCALE#*43)
Text=Lv: 99
FontFace=#thickFont#
FontSize=(#SCALE#*15)
FontColor=64,61,52,255
StringAlign=Left
AntiAlias=1
 
[Text.Bottom]
Meter=String
X=(#SCALE#*110)
Y=(#SCALE#*315)
Text=No error
StringCase=Upper
FontFace=#thickFont#
FontSize=(#SCALE#*15)
FontColor=64,61,52,255
StringAlign=Left
AntiAlias=1
 
[measureLabelDisk1]
Measure=FreeDiskSpace
Drive=#disk1#:
Label=1
Substitute="":"0"
IfCondition=(mLabel = 0)
IfTrueAction=[!SetOption "Text.HDD" "Text" "#disk1#:"][!Update]
IfFalseAction=[!SetOption "Text.HDD" "Text" "#disk1#: %1"][!Update]
 
[measureTotalDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
Total=1
UpdateDivider=-1
 
[measureUsedDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
InvertMeasure=1
UpdateDivider=60
 
[measureTotalDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
Total=1
UpdateDivider=-1

[measureUsedDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
InvertMeasure=1
UpdateDivider=60
 
[MeasureSkinPosition]
Measure=Calc
Formula=1
OnUpdateAction=[!Move (#CURRENTCONFIGX#-210) (#CURRENTCONFIGY#) "#ROOTCONFIG#\Disk sub" "2 Disks sub.ini"]
UpdateDivider=-1
DynamicVariables=1
 
;;=======================================
;  Meters
;;========================================

[meterDriver]
Meter=STRING
X=(#SCALE#*30)
Y=(#SCALE#*220)
Text=DISKS
StringCase=Upper
FontFace=#thickFont#
FontSize=(#SCALE#*12)
FontColor=64,61,52, 255
Angle=(PI/2)
AntiAlias=1

[meterLabelDisk1]
Meter=STRING
MeterStyle=styleLeftText
X=(#SCALE#*40)
Y=(#SCALE#*210)
Text=#disk1#
MouseOverAction=[!SetOption "meterLabelDisk1" "StringStyle" "Bold"][!UpdateMeter "meterLabelDisk1"][!Redraw]
MouseLeaveAction=[!SetOption "meterLabelDisk1" "StringStyle" ""][!UpdateMeter "meterLabelDisk1"][!Redraw]
LeftMouseUpAction=#disk1#

[meterValueDisk1]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measureUsedDisk1
MeasureName2=measureTotalDisk1
X=(#SCALE#*290)
Y=(#SCALE#*210)
Percentual=0
Text=%1B/%2B
; %1 stands for the value of MeasureName (measureUsedDisk1 in this case).
; %2 stands for the value of MeasureName2.
NumOfDecimals=0
Autoscale=1
; Because disk measures return the free/used space in bytes, we must use AutoScale=1 to
; automatically scale the value into a more readable figure.

[meterBarDisk1]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureUsedDisk1
X=(#SCALE#*40)
Y=4R

[meterLabelDisk2]
Meter=STRING
MeterStyle=styleLeftText
X=(#SCALE#*40)
Y=15R
Text=#disk2#
MouseOverAction=[!SetOption "meterLabelDisk2" "StringStyle" "Bold"][!UpdateMeter "meterLabelDisk2"][!Redraw]
MouseLeaveAction=[!SetOption "meterLabelDisk2" "StringStyle" ""][!UpdateMeter "meterLabelDisk2"][!Redraw]
LeftMouseUpAction=#disk2#

[meterValueDisk2]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measureUsedDisk2
MeasureName2=measureTotalDisk2
X=(#SCALE#*290)
Y=0r
Percentual=0
Text=%1B/%2B
NumOfDecimals=0
Autoscale=1

[meterBarDisk2]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureUsedDisk2
X=(#SCALE#*40)
Y=2R

[measureSystem]
Meter=STRING
X=(#SCALE#*30)
Y=(#SCALE#*100)
Text=System
StringCase=Upper
FontFace=#thickFont#
FontSize=(#SCALE#*12)
FontColor=64,61,52,255
Angle=(PI/2)
AntiAlias=1

[measureCPU]
;;This measure returns the average CPU load between all cores.
Measure=CPU
Processor=0

[measureRAM]
;;Returns the amount of RAM used in bytes.
Measure=PhysicalMemory
UpdateDivider=20
;;UpdateDivider sets the rate at which the value of the measure is updated. It is
;;Calculated as follows: UpdateDivider x Update. In this case, Update is set to
;;1000 milliseconds (in the [Rainmeter] section). 1000 x 20 = 20000 ms or 20 seconds.

[measureRAMTotal]
;;Returns the amount of RAM used in bytes.
Measure=PhysicalMemory
Total=1
UpdateDivider=20

[measureSWAP]
;;Returns the amount of SWAP (pagefile) used in bytes.
Measure=SWAPMemory
UpdateDivider=120

[MeasureSkinPosition]
Measure=Calc
Formula=1
OnUpdateAction=[!Move (#CURRENTCONFIGX#-210) (#CURRENTCONFIGY#) "#ROOTCONFIG#\System sub"]
UpdateDivider=-1
DynamicVariables=1

[meterLabelCPU]
Meter=STRING
MeterStyle=styleLeftText
X=(#SCALE#*40)
Y=(#SCALE#*80)
Text=CPU
LeftMouseUpAction="taskmgr.exe"
MouseOverAction=[!SetOption "meterLabelCPU" "StringStyle" "Bold"][!UpdateMeter "meterLabelCPU"][!Redraw]
MouseLeaveAction=[!SetOption "meterLabelCPU" "StringStyle" ""][!UpdateMeter "meterLabelCPU"][!Redraw]

[meterValueCPU]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measureCPU
X=(#SCALE#*290)
Y=0r
Text=%1%


[meterBarCPU]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureCPU
X=(#SCALE#*40)
Y=2R

[meterLabelRAM]
Meter=STRING
MeterStyle=styleLeftText
X=(#SCALE#*40)
Y=10R
Text=RAM


[meterValueRAM]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measureRAM
MeasureName2=measureRAMTotal
X=(#SCALE#*290)
Y=0r
Text=%1B/%2B
Autoscale=1

[meterBarRAM]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureRAM
X=(#SCALE#*40)
Y=2R

[meterLabelSWAP]
Meter=STRING
MeterStyle=styleLeftText
X=(#SCALE#*40)
Y=10R
Text=SWAP

[meterValueSWAP]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measureSWAP
X=(#SCALE#*290)
Y=0r
Text=%1B
Autoscale=1
[meterBarSWAP]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureSWAP
X=(#SCALE#*40)
Y=2R

[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
MiddleMouseUpAction=!Refresh #CURRENTCONFIG#

RightMouseUpAction=[!SkinCustomMenu]

ContextTitle=Edit Variables
ContextAction=["#@#\disk.inc"]

ContextTitle2=----
ContextAction2=[]

ContextTitle3=Smaller Size (0.8)
ContextAction3=[!WriteKeyValue Variables SCALE "(#SCREENAREAWIDTH#*0.000520833333325754-0.2)"][!Refresh]

ContextTitle4=Normal Size (1.0)
ContextAction4=[!WriteKeyValue Variables SCALE "(#SCREENAREAWIDTH#*0.000520833333325754)"][!Refresh]

ContextTitle5=Bigger Size (1.2)
ContextAction5=[!WriteKeyValue Variables SCALE "(#SCREENAREAWIDTH#*0.000520833333325754+0.2)"][!Refresh]

ContextTitle6=----
ContextAction6=[]

ContextTitle7=Standard Context Menu
ContextAction7=[!SkinMenu]
