[Rainmeter]
Update=1000
[Metadata]
Name=Welcome
Author=Amtia
Information=Welcome
Version=1.0
License=CC BY-NC-SA 4.0

;;==========================================
;  Measures
;;==========================================

[MeasureTime]
; This measure returns the time in a 24-hour format (i.e. HH:MM).
Measure=Time
Format=%H:%M
; For a 12-hour clock, change the Format option above to: %I:%M %p
; Refer to the Rainmeter manual for other format codes.

[MeasureDate]
; Returns the date as DD.MM.YYYY
Measure=Time
Format=%d.%m.%Y

[MeasureDay]
; Returns the current day
Measure=Time
Format=%A

[MeasureSec]
measure=Time
format=%S


;;==========================================
;  Styles
;;==========================================

[UpperShape_SD]
Meter=Shape
Shape=Rectangle 0,0,230,200 | FillColor 77,73,62,200| StrokeWidth 0
X=5
Y=5

[LowerShape_SD]
Meter=Shape
Shape=Rectangle 0,0,230,50 | FillColor 77,73,62,200| StrokeWidth 0
X=5
Y=155

[UpperShape]
Meter=Shape
Shape=Rectangle 0,0,230,200 | FillColor 64,61,52| StrokeWidth 0

[LowerShape]
Meter=Shape
Shape=Rectangle 0,0,230,50 | FillColor 217,213,196| StrokeWidth 0
Y=150

;;==========================================
;  Meters
;;==========================================

[MeterDate]
MeasureName=MeasureDate
Meter=STRING
StringCase=Upper
X=115
Y=157
FontColor=70,65,57
FontSize=27
FontFace=Gibson
StringAlign=CENTER
AntiAlias=1

[MeterTime]
MeasureName=MeasureTime
Meter=STRING
X=118
Y=80
FontColor=217,213,196
FontSize=50
FontFace=Gibson
StringAlign=CENTER
;StringStyle=BOLD
AntiAlias=1

[MeterDay]
MeasureName=MeasureDay
Meter=STRING
StringCase=Upper
X=118
Y=42
FontColor=217,213,196
FontSize=17
FontFace=Gibson
StringAlign=CENTER
AntiAlias=1

[MeterShapes]
Meter=Shape
Shape=Line 15,73,220,73 | StrokeColor 217,213,196 | StrokeWidth 2

[Image]
Meter=IMAGE
ImageName=#@#Underlay\arrow.png
X=103
Y=10
AntiAlias=1