[Rainmeter]
Update=1000
AccurateText=1

[Variables]
@IncludeTasks="#CURRENTPATH#Tasks.inc"

CardW=210
TopH=22
BotH=118
Radius=5
ColorTop=76,35,13
ColorBot=59,26,9,160
ColorTextTitle=255,255,255,220
ColorText=255,255,255,255
ColorHover=245,176,65
Scale=1

[Bg]
Meter=Shape
Shape=Rectangle 0,0,(#CardW#*#Scale#),((#TopH#+#BotH#)*#Scale#),(#Radius#*#Scale#) | FillColor #ColorBot# | StrokeWidth 0
Shape2=Rectangle 0,0,(#CardW#*#Scale#),(#TopH#*#Scale#),(#Radius#*#Scale#) | FillColor #ColorTop# | StrokeWidth 0
Shape3=Rectangle 0,((#TopH#-#Radius#)*#Scale#),(#CardW#*#Scale#),(#Radius#*#Scale#) | FillColor #ColorTop# | StrokeWidth 0
DynamicVariables=1

[Title]
Meter=String
Text="TO DO LIST"
X=((#CardW#/2)*#Scale#)
Y=((#TopH#/2)*#Scale#)
StringAlign=CenterCenter
FontWeight=700
FontSize=(9*#Scale#)
FontColor=#ColorTextTitle#
AntiAlias=1

; --- INPUT TEXT PLUGIN ---
[MeasureInput]
Measure=Plugin
Plugin=InputText
X=(25*#Scale#)
Y=0
W=((#CardW#-30)*#Scale#)
H=(16*#Scale#)
FontSize=(8*#Scale#)
FontColor=#ColorText#
SolidColor=59,26,9,255
StringAlign=LeftCenter
AntiAlias=1
FocusDismiss=1
DefaultValue="[#CurrentTask]"
Command1=[!WriteKeyValue Variables "#CurrentVar#" "$UserInput$" "#CURRENTPATH#Tasks.inc"][!SetVariable "#CurrentVar#" "$UserInput$"][!Refresh]

; --- STYLES ---
[StyleBullet]
Text="•"
X=(10*#Scale#)
Y=(20*#Scale#)r
FontSize=(10*#Scale#)
FontWeight=700
FontColor=#ColorHover#
AntiAlias=1
StringAlign=LeftCenter

[StyleTaskText]
X=(12*#Scale#)r
Y=0r
W=((#CardW#-35)*#Scale#)
ClipString=1
FontSize=(8*#Scale#)
FontColor=#ColorText#
AntiAlias=1
SolidColor=0,0,0,1
MouseOverAction=[!SetOption #CURRENTSECTION# FontColor "#ColorHover#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# FontColor "#ColorText#"][!UpdateMeter #CURRENTSECTION#][!Redraw]

; --- TASK 1 ---
[Bullet1]
Meter=String
MeterStyle=StyleBullet
Y=((#TopH# + 12)*#Scale#)

[Text1]
Meter=String
MeterStyle=StyleTaskText
Text="#Task1#"
LeftMouseUpAction=[!SetVariable CurrentTask "#Task1#"][!SetVariable CurrentVar "Task1"][!SetOption MeasureInput Y "([Text1:Y]-8*#Scale#)"][!CommandMeasure "MeasureInput" "ExecuteBatch 1"]
DynamicVariables=1

; --- TASK 2 ---
[Bullet2]
Meter=String
MeterStyle=StyleBullet

[Text2]
Meter=String
MeterStyle=StyleTaskText
Text="#Task2#"
LeftMouseUpAction=[!SetVariable CurrentTask "#Task2#"][!SetVariable CurrentVar "Task2"][!SetOption MeasureInput Y "([Text2:Y]-8*#Scale#)"][!CommandMeasure "MeasureInput" "ExecuteBatch 1"]
DynamicVariables=1

; --- TASK 3 ---
[Bullet3]
Meter=String
MeterStyle=StyleBullet

[Text3]
Meter=String
MeterStyle=StyleTaskText
Text="#Task3#"
LeftMouseUpAction=[!SetVariable CurrentTask "#Task3#"][!SetVariable CurrentVar "Task3"][!SetOption MeasureInput Y "([Text3:Y]-8*#Scale#)"][!CommandMeasure "MeasureInput" "ExecuteBatch 1"]
DynamicVariables=1

; --- TASK 4 ---
[Bullet4]
Meter=String
MeterStyle=StyleBullet

[Text4]
Meter=String
MeterStyle=StyleTaskText
Text="#Task4#"
LeftMouseUpAction=[!SetVariable CurrentTask "#Task4#"][!SetVariable CurrentVar "Task4"][!SetOption MeasureInput Y "([Text4:Y]-8*#Scale#)"][!CommandMeasure "MeasureInput" "ExecuteBatch 1"]
DynamicVariables=1

; --- TASK 5 ---
[Bullet5]
Meter=String
MeterStyle=StyleBullet

[Text5]
Meter=String
MeterStyle=StyleTaskText
Text="#Task5#"
LeftMouseUpAction=[!SetVariable CurrentTask "#Task5#"][!SetVariable CurrentVar "Task5"][!SetOption MeasureInput Y "([Text5:Y]-8*#Scale#)"][!CommandMeasure "MeasureInput" "ExecuteBatch 1"]
DynamicVariables=1
